spring:
  profiles: 
  active: local
  application:
    name: commonGwConf

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

zuul:
  routes:
    schoolSvc:
#      path: /schoolSvc/**
      serviceId: school-service

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    enabled: false

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
---
spring:
  profiles: local

info:
  description: Gateway
  url: http://localhost:10001
---
