spring:  
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
#          uri: https://github.com/sunnykor/microservice.git
          uri: file://E:/Git/localGit
          searchPaths: configurations/demo
server:  
  address: 192.168.56.1
  port: 8888